# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Georeferencer
                                 A QGIS plugin
 This plugin georeference the image
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-09
        copyright            : (C) 2022 by Deepak Parajuli
        email                : deepak.parajuli002@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Georeferencer class from file Georeferencer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_ref import Georeferencer
    return Georeferencer(iface)
